"""Initial migration

Revision ID: 310b56c5744a
Revises: 
Create Date: 2025-06-26 09:23:27.272764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310b56c5744a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('album', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('albums_pkey')),
    sa.UniqueConstraint('rank', name=op.f('albums_rank_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
